### PR TITLE
Simplify node-density

### PR DESCRIPTION
**Pull request by rsevilla87**
Simplified version of the ICNI2 node-density workload:

- [x] ICNI2
- [x] ICNI1
- [x] Mixed

It makes use of podWait: true in order to wait for pods to be ready between iterations, that way the generated workload can be compared with the original one.

cc: @josecastillolema @mukrishn @mohit-sheth

Signed-off-by: Raul Sevilla <rsevilla@redhat.com>

### CODE REVIEW

**Comment by mohit-sheth** [comment]
looks good and should have the same effect. Although would want Murali and Jose to confirm

**Comment by venkataanil** [comment]
@rsevilla87 Can you please reopen this PR. This one looks more efficient rather than creating a job for each iteration.

**Comment by josecastillolema** [comment]
Thanks @rsevilla87  and @venkataanil, any simplification of the templates is super well received.
The only think we have to be aware is backwards compatibility.
If this PR decreases the total time of the experiment we have to make sure there is no noticeable impact in the reported pod creation latency times (and in the total object count).

**Comment by smalleni** [comment]
There is a reason we had done this but I can't recall why at this point. But agree, a single job with jobIterations and podWait can have a similar effect instead of using multiple jobs with waitWhenFinished.  However, the equivalent of a jobPause parameter is not available for iterations - perhaps a moot point as the current jobPause is 0. Is there a scenario where we would want to introduce some deal to ease the overall load/deal with backpressure in the future?

**Pull request closed without merging**
